version: "3"
services:
  db:
    build: .
    image: mysql-examen-fullstack:1.0.3
    container_name: mysql-examen-fullstack
    ports:
       - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456